clusters:
  - name: default
    services:
      - helloworld

services:
  - name: helloworld
    task_name: helloworld
    task_version: 4
    min: 3
    max: 7
    desired: 7

    # experimental
    # constraints:
    #  - host.name = 'x'
    #  - unique host.name
    #  - host.tags.x = 'y'
    #  - group_by host.tags.x

tasks:
  - name: helloworld
    version: 4
    provide_port: true
    containers:
      - name: helloworld
        type: docker

        executor:
          container_port: 80
          name: helloworld
          image: tutum/hello-world

        checks:
          - http: http://127.0.0.1:$PROVIDED_PORT
            interval: 10s
            timeout: 5s
