clusters:
  - name: default
    deployments:
      - helloworld

services:
  - name: helloworld-default
    cluster: default

deployments:
  - name: helloworld
    task_name: helloworld
    task_version: 4
    min: 3
    max: 7
    desired: 7
    max_attempts: 20

tasks:
  - name: helloworld
    version: 4
    provide_port: true
    containers:
      - name: helloworld
        type: docker

        ports:
          - name: main
            host: 0
            container: 80

        executor:
          name: helloworld
          image: tutum/hello-world

        checks:
          - http: http://127.0.0.1:$main
            interval: 10s
            timeout: 5s
