clusters:
  - name: default
    scheduler: default
    services:
      - helloworld

services:
  - name: helloworld
    task_name: helloworld
    task_version: 2
    min: 3
    max: 50
    desired: 50

tasks:
  - name: helloworld
    version: 2
    tags:
      - urlprefix-/helloworld

    provide_port: true

    containers:
      - name: helloworld
        type: docker
        executor:
          name: helloworld
          image: tutum/hello-world

        checks:
          - http: http://127.0.0.1:$PROVIDED_PORT
            interval: 10s
