clusters:
  - name: default
    services:
      - helloworld

services:
  - name: helloworld
    task_name: helloworld
    task_version: 1
    min: 2
    max: 8
    desired: 2

tasks:
  - name: helloworld
    version: 1
    provide_port: true
    checks:
      - http: http://127.0.0.1
        interval: 10s
        add_provided_port: true

    containers:
      - name: helloworld
        executor: docker
        docker:
          name: helloworld
          image: tutum/hello-world
          container_port: 80
