clusters:
  - name: default
    scheduler: default
    services:
      - helloworld
#      - lb

services:
  - name: helloworld
    task_name: helloworld
    task_version: 1
    min: 2
    max: 8
    desired: 2

  - name: lb
    task_name: lb
    task_version: 2
    min: 1
    max: 1
    desired: 1

tasks:
  - name: lb
    version: 2
    port: 9999
    checks:
      - http: http://127.0.0.1:9999
        interval: 10s

    containers:
      - name: lb
        executor: docker
        docker:
          name: lb
          image: magiconair/fabio
          ports:
            - 9999:9999
          flags:
            - --net=host

  - name: helloworld
    version: 1
    tags:
      - urlprefix-/

    provide_port: true
    checks:
      - http: http://127.0.0.1
        interval: 10s
        add_provided_port: true

    containers:
      - name: helloworld
        executor: docker
        docker:
          name: helloworld
          image: tutum/hello-world
          container_port: 80
