clusters:
  - name: default
    scheduler: default
    services:
      - helloworld
      - lb

services:

  # Services are identified by a name, task name and task version. Services are what
  # execute the tasks. They take a basic configuration to let the scheduler know the
  # leniency and priorities for scheduling a specific task. Services can be frequently
  # updated, and their configuration takes place immediately.
  #
  # An instance of a running service will be registered in consul with the name: <cluster>-<service>,
  # and the id: <cluster>-<service>-<task_version>-<instance>

  - name: helloworld        # unique service name, for dns registry as well
    task_name: helloworld   # task to run
    task_version: 2         # the task version to use, allows for incremental deployments
    min: 2                  # the minimum amount of the task to run
    max: 3                  # the maximum amount of the task to run
    desired: 3              # the desired amount to run

  - name: lb
    task_name: lb
    task_version: 2
    min: 0
    max: 1
    desired: 1

tasks:
  - name: lb
    version: 2
    port: 9999
    checks:
      - http: http://127.0.0.1:9999/helloworld
        interval: 10s

    containers:
      - name: lb
        executor: bash
        bash:
          start:
            - daemonize /usr/local/bin/fabio
          stop:
            - kill $(lsof -t -i:9999)

  - name: helloworld
    version: 2
    tags:
      - urlprefix-/helloworld

    provide_port: true
    checks:
      - http: http://127.0.0.1
        interval: 10s
        add_provided_port: true

    containers:
      - name: helloworld
        executor: docker
        docker:
          name: helloworld
          image: tutum/hello-world
          container_port: 80
