clusters:
  - name: default
    scheduler: default
    services:
      - helloworld
      - lb

services:
  - name: helloworld
    task_name: helloworld
    task_version: 2
    min: 2
    max: 3
    desired: 3

  - name: lb
    task_name: lb
    task_version: 2
    min: 0
    max: 1
    desired: 1

tasks:
  - name: lb
    version: 2
    port: 9999
    checks:
      - http: http://127.0.0.1:9999/helloworld
        interval: 10s

    containers:
      - name: lb
        executor: bash
        bash:
          start:
            - daemonize /usr/local/bin/fabio
          stop:
            - kill $(lsof -t -i:9999)

  - name: helloworld
    version: 2
    tags:
      - urlprefix-/helloworld

    provide_port: true
    checks:
      - http: http://127.0.0.1
        interval: 10s
        add_provided_port: true

    containers:
      - name: helloworld
        executor: docker
        docker:
          name: helloworld
          image: tutum/hello-world
          container_port: 80
