#!/usr/bin/env bash

go install github.com/coldog/sked
env GOOS=linux GOARCH=amd64 go build -o tests/sked_linux-amd64-latest github.com/coldog/sked
docker build -t sked-testing tests
rm tests/sked_linux-amd64-latest

docker network create --subnet 172.25.0.0/16 sked-net

for i in 1 2 3 4 5 6 7
do
    consul_id=consul-${i}
    addr=172.25.0.1${i}
    serve=""
    expect=""
    ui=""
    ports=""

    if [ ${i} = "1" ]; then
        ui="-ui"
        ports="-p=8500:8500"
    fi

    if (( $i < 4 )); then
        serve="-server"
    fi

    if (( $i < 4 )); then
        expect="-bootstrap-expect=3"
    fi

    docker run \
        -d -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' \
        --net=sked-net \
        --net-alias=${consul_id} \
        --ip=${addr} \
        --name=${consul_id} \
        ${ports} \
        consul agent ${serve} -node=${consul_id} -advertise=${addr} ${ui} -client=0.0.0.0 ${expect}
done

docker exec -it consul-1 consul join 172.25.0.12 172.25.0.13 172.25.0.14 172.25.0.15 172.25.0.16 172.25.0.17

for i in 1 2 3 4 5 6 7
do
    docker run -d --net=sked-net --name=sked-${i} --net-alias=sked-${i} -p 823${i}:8231 -e CONSUL_API=172.25.0.1${i}:8500 \
        sked-testing sked --advertise=sked-${i}:8231 combined
done
